# Generated by Django 4.0.4 on 2022-04-18 22:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="início"
                    ),
                ),
                ("end_date", models.DateTimeField(verbose_name="término")),
                (
                    "judge_vote_weight",
                    models.IntegerField(
                        default=1,
                        help_text='Exemplo: se especificado "3" e o jurado votar "5", o voto será computado como 15.',
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="peso do voto dos jurados",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created date"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "judges",
                    models.ManyToManyField(
                        blank=True,
                        related_name="judges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="jurados",
                    ),
                ),
            ],
            options={
                "verbose_name": "concurso",
                "verbose_name_plural": "concursos",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                ("work", models.CharField(max_length=255, verbose_name="trabalho")),
                ("description", models.TextField(verbose_name="descrição")),
                ("video_url", models.URLField(verbose_name="URL do vídeo")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created date"
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contest.contest",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "participante",
                "verbose_name_plural": "participantes",
                "unique_together": {("name", "contest")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created date"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contest.participant",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "voto",
                "verbose_name_plural": "votos",
                "unique_together": {("registered_by", "participant")},
            },
        ),
    ]
