# Generated by Django 4.0.4 on 2022-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
    ]
