# Generated by Django 4.0.4 on 2022-04-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_last_forgotpassword_request',
            field=models.DateTimeField(editable=False, null=True, verbose_name='última solicitação de redefinição de senha'),
        ),
    ]
