# Generated by Django 4.0.4 on 2022-04-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_date_last_forgotpassword_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_last_activationemail_request',
            field=models.DateField(editable=False, null=True, verbose_name='última solicitação de e-mail de ativação'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='e-mail'),
        ),
    ]
