# Generated by Django 4.0.4 on 2022-04-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_date_last_activationemail_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_last_activationemail_request',
            field=models.DateTimeField(editable=False, null=True, verbose_name='última solicitação de e-mail de ativação'),
        ),
    ]
